aws_region     = "us-east-1"
aws_profile    = "default"
name           = "dish"
vpc_cidr       = "10.10.0.0/16"
azs            = ["us-east-1a", "us-east-1b"]
public_subnets = ["10.10.1.0/24", "10.10.2.0/24"]
instance_type  = "t3.micro"
key_name       = "my-keypair"
aws_profile = "mahesh"
