replicaCount: 2

image:
  repository: maheshprince/firstwebapp
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

env:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_MESSAGE: "Welcome to FinanceMe App"

secret:
  DB_USERNAME: root
  DB_PASSWORD: mysecurepassword

blueGreen:
  version: blue      # change to green during rollout

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpu: 60
