replicaCount: 2

image:
  repository: maheshprince/firstwebapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8082
  targetPort: 8082
  nodePort: 30081

resources: {}





