replicaCount: 1

image:
  repository: maheshprince/firstwebapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8081
  nodePort: 30080

resources: {}


