apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "financeme.fullname" . }}-{{ .Values.blueGreen.version }}
  labels:
    app: {{ include "financeme.name" . }}
    version: {{ .Values.blueGreen.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "financeme.name" . }}
      version: {{ .Values.blueGreen.version }}
  template:
    metadata:
      labels:
        app: {{ include "financeme.name" . }}
        version: {{ .Values.blueGreen.version }}
    spec:
      containers:
      - name: financeme
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ include "financeme.fullname" . }}-config
        - secretRef:
            name: {{ include "financeme.fullname" . }}-secret
