- name: Setup single-node Kubernetes host on Ubuntu
  hosts: k8s_host
  become: yes

  tasks:
    - name: Apt update/upgrade
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install base utilities
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - socat
          - conntrack
          - ebtables
          - ethtool
          - unzip
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # Kube prerequisites
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb | int > 0
    - name: Remove swap from fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#]\S*\s+)\S+\s+swap\s+'
        replace: '# \1 none swap sw 0 0'

    - name: Ensure br_netfilter is enabled
      modprobe:
        name: br_netfilter
        state: present

    - name: Set sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
    - name: Apply sysctl
      command: sysctl --system

    - name: Add Kubernetes apt key & repo
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' > /etc/apt/sources.list.d/kubernetes.list
        apt-get update

    - name: Install kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold kube packages
      apt:
        name: "{{ item }}"
        state: present
        
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Initialize Kubernetes control-plane (single node)
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create kube config for ubuntu user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown -R ubuntu:ubuntu /home/ubuntu/.kube

    - name: Install Flannel CNI
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

    - name: Taint master to allow scheduling pods (single-node)
      become_user: ubuntu
      shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane- || true

    - name: Install Helm
      shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

